### ISSUE TITLE
question about the version

### ISSUE THREAD

**Issue by SeekingDream** [Henrygwb/Explaining-DL#1]
` model = load_model('target_model/O0_Bi_Rnn.h5')`
when I run this code, there is an error as follows: 
`Traceback (most recent call last):
  File "F:/Machine Model/Explaining-DL-master/lemna/lemna_beta.py", line 263, in <module>
    model = load_model('F:/Machine Model/Explaining-DL-master/lemna/target_model/O0_Bi_Rnn.h5')
  File "F:\Python\anacondapy3.5\file\lib\site-packages\keras\engine\saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "F:\Python\anacondapy3.5\file\lib\site-packages\keras\engine\saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "F:\Python\anacondapy3.5\file\lib\site-packages\keras\engine\saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "F:\Python\anacondapy3.5\file\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "F:\Python\anacondapy3.5\file\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "F:\Python\anacondapy3.5\file\lib\site-packages\keras\engine\sequential.py", line 301, in from_config
    model.add(layer)
  File "F:\Python\anacondapy3.5\file\lib\site-packages\keras\engine\sequential.py", line 181, in add
    output_tensor = layer(self.outputs[0])
  File "F:\Python\anacondapy3.5\file\lib\site-packages\keras\layers\wrappers.py", line 427, in __call__
    return super(Bidirectional, self).__call__(inputs, **kwargs)
  File "F:\Python\anacondapy3.5\file\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "F:\Python\anacondapy3.5\file\lib\site-packages\keras\layers\wrappers.py", line 522, in call
    y = self.forward_layer.call(inputs, **kwargs)
  File "F:\Python\anacondapy3.5\file\lib\site-packages\keras\layers\recurrent.py", line 1072, in call
    initial_state=initial_state)
  File "F:\Python\anacondapy3.5\file\lib\site-packages\keras\layers\recurrent.py", line 649, in call
    input_length=timesteps)
  File "F:\Python\anacondapy3.5\file\lib\site-packages\keras\backend\tensorflow_backend.py", line 3011, in rnn
    maximum_iterations=input_length)`

`TypeError: while_loop() got an unexpected keyword argument 'maximum_iterations'`

I guess this may be the cause of different version of python and tensorflow. so I want to ask which version I should chose. my python version is 3.5 and my tensorflow version is 1.3.0.

**Comment by Henrygwb** [comment]
Python: 2.7
keras: 2.1.6
Tensorflow: 1.2.0
Theano: 0.9.0
